spring.application.name=EstoqueFacil

spring.config.import=optional:file:.env.properties
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.mode=HTML5
spring.thymeleaf.cache=false 
spring.thymeleaf.encoding=UTF-8
spring.thymeleaf.content-type=text/html
spring.thymeleaf.check-template-location=true
spring.thymeleaf.enabled=true
spring.datasource.url=jdbc:mysql://${MYSQL_HOST}:3306/${MYSQL_DATABASE}
spring.datasource.username=${MYSQL_USER}
spring.datasource.password=${MYSQL_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
#spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
mail.smtp.host=${MAIL_HOST:smtp.gmail.com}
mail.smtp.port=${MAIL_PORT:587}
mail.smtp.username=${MAIL_USERNAME}
mail.smtp.password=${MAIL_PASSWORD}


# Dados do Gerente Padrão
gerente.inicial.nome=${GERENTE_NOME}
gerente.inicial.cpf=${GERENTE_CPF}
gerente.inicial.email=${GERENTE_EMAIL}
gerente.inicial.senha=${GERENTE_SENHA}

# Endereço do Gerente
gerente.inicial.endereco.rua=${GERENTE_RUA}
gerente.inicial.endereco.numero=${GERENTE_NUMERO}
gerente.inicial.endereco.cidade=${GERENTE_CIDADE}
gerente.inicial.endereco.estado=${GERENTE_ESTADO}
gerente.inicial.endereco.cep=${GERENTE_CEP}
gerente.inicial.endereco.bairro=${GERENTE_BAIRRO}

# Telefone do Gerente
gerente.inicial.telefone.numero=${GERENTE_TEL}
gerente.inicial.telefone.tipo=${GERENTE_TEL_TIPO}


# Mapeamento do Setor Gerência
setor.gerencia.nome=${SETOR_GERENCIA_NOME}
setor.gerencia.capacidade=${SETOR_GERENCIA_CAPACIDADE}
setor.gerencia.tipo=${SETOR_GERENCIA_TIPO}
setor.gerencia.endereco.rua=${SETOR_GERENCIA_RUA}
setor.gerencia.endereco.numero=${SETOR_GERENCIA_NUMERO}
setor.gerencia.endereco.cidade=${SETOR_GERENCIA_CIDADE}
setor.gerencia.endereco.estado=${SETOR_GERENCIA_ESTADO}
setor.gerencia.endereco.cep=${SETOR_GERENCIA_CEP}
setor.gerencia.endereco.bairro=${SETOR_GERENCIA_BAIRRO}

# Mapeamento do Setor Almoxarife
setor.almoxarifado.nome=${SETOR_ALMOX_NOME}
setor.almoxarifado.capacidade=${SETOR_ALMOX_CAPACIDADE}
setor.almoxarifado.tipo=${SETOR_ALMOX_TIPO}
setor.almoxarifado.endereco.rua=${SETOR_ALMOX_RUA}
setor.almoxarifado.endereco.numero=${SETOR_ALMOX_NUMERO}
setor.almoxarifado.endereco.cidade=${SETOR_ALMOX_CIDADE}
setor.almoxarifado.endereco.estado=${SETOR_ALMOX_ESTADO}
setor.almoxarifado.endereco.cep=${SETOR_ALMOX_CEP}
setor.almoxarifado.endereco.bairro=${SETOR_ALMOX_BAIRRO}

# Mapeamento do Setor Financeiro
setor.financeiro.nome=${SETOR_FIN_NOME}
setor.financeiro.capacidade=${SETOR_FIN_CAPACIDADE}
setor.financeiro.tipo=${SETOR_FIN_TIPO}
setor.financeiro.endereco.rua=${SETOR_FIN_RUA}
setor.financeiro.endereco.numero=${SETOR_FIN_NUMERO}
setor.financeiro.endereco.cidade=${SETOR_FIN_CIDADE}
setor.financeiro.endereco.estado=${SETOR_FIN_ESTADO}
setor.financeiro.endereco.cep=${SETOR_FIN_CEP}
setor.financeiro.endereco.bairro=${SETOR_FIN_BAIRRO}

spring.docker.compose.enabled=true
spring.docker.compose.lifecycle-management=start-and-stop
spring.mvc.log-resolved-exception=true


# Disable Spring Security autoconfiguration
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
spring.jackson.deserialization.fail-on-null-for-primitives=false